[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$GIPQeo9xTmkt5bw3ZkyplQ$5WOUHNGgPFr9EdBbY/0xnVSN6rcwmpwQsekU.nGpN.Sk/sXj143ua2MI6.nuupctZ.rxTljYDksZkP2u8CGwww
logfile = /var/log/odoo/odoo.log
xmlrpc_port = 8069
longpolling_port = 8072
workers = 0
proxy_mode = False
data_dir = /var/lib/odoo

