[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$gxBiTAmhdK6V0vp/b41xzg$PyTKK8m3.D4BQCuktK/rSQFTqcMEvEfOcMmpBN4x7or04C2tHSkaVDiH9Kxf6K0RqB7SmaCiUuJZXSX0hMU7CA
logfile = /var/log/odoo/odoo.log
xmlrpc_port = 8069
longpolling_port = 8072
workers = 0
proxy_mode = False
data_dir = /var/lib/odoo

