[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$tFaqdc7ZOyckhJCy9t77Xw$U3ANPm2zDIigQAz5GvN8Dp0Ymi/T/BmBcriO9LtzFo/xFa.NUpadMky/T74dgKTX6zz7nhOICKz2jfwO.fiWZw
logfile = /var/log/odoo/odoo.log
xmlrpc_port = 8069
longpolling_port = 8072
workers = 0
proxy_mode = False
data_dir = /var/lib/odoo

